# Generated by Django 4.2.7 on 2026-03-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_currency'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id'], name='orders_orde_user_id_a87c6f_idx'),
        ),
    ]
