# Generated by Django 4.2.7 on 2026-03-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orders_orde_user_id_a87c6f_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_user_id_a87c6f_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id', 'status', 'created_at'], name='orders_orde_user_id_0886b9_idx'),
        ),
    ]
