# Generated by Django 4.2.7 on 2026-01-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('order_id', models.UUIDField(unique=True)),
                ('status', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='readmodels__user_id_228233_idx')],
            },
        ),
    ]
