# Generated by Django 4.2.7 on 2026-01-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersbyuser',
            name='currency',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
