# Generated by Django 4.2.7 on 2026-01-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['published', 'created_at'], name='outbox_outb_publish_2a4688_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['aggregate_id'], name='outbox_outb_aggrega_ced855_idx'),
        ),
    ]
