# Generated by Django 4.2.7 on 2026-02-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0002_outboxevent_outbox_outb_publish_2a4688_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
    ]
