# Generated by Django 4.2.7 on 2026-03-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0003_outboxevent_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
