# Generated by Django 4.2.7 on 2026-03-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0004_outboxevent_failed_outboxevent_retry_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='outboxevent',
            name='outbox_outb_publish_2a4688_idx',
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['published', 'consumed', 'failed', 'created_at'], name='outbox_outb_publish_d1602c_idx'),
        ),
    ]
