# Generated by Django 4.2.7 on 2026-04-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0005_remove_outboxevent_outbox_outb_publish_2a4688_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_id'], name='outbox_proc_event_i_7be00f_idx')],
            },
        ),
    ]
